### ISSUE TITLE
使用最新的jdk1.8.0_141版本进行加解密报错！

### ISSUE THREAD

**Issue by zzgf16** [cuter44/wxpay-sdk#23]
已经升级了jce的两个jar包，之后用这个JDK启动后，还是报错，具体堆栈信息如下：
ERROR c.f.fxl.web.m.api.v2.UserController - java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Usage constraint TLSServer check failed: SHA1 used with certificate: CN=GeoTrust Global CA, O=GeoTrust Inc., C=US.  Usage was tls server
	at com.github.cuter44.wxmp.util.TokenKeeper.retrieveAccessToken(TokenKeeper.java:89)
	at com.github.cuter44.wxmp.util.TokenKeeper.getAccessToken(TokenKeeper.java:111)
	at com.github.cuter44.wxmp.util.TokenKeeper.retrieveJSSDKTicket(TokenKeeper.java:120)
	at com.github.cuter44.wxmp.util.TokenKeeper.getJSSDKTicket(TokenKeeper.java:149)
	at com.fangxuele.fxl.util.wx.WxmpUtil.getWxJssdkParam(WxmpUtil.java:58)
	at com.fangxuele.fxl.service.v2.CustomerService.getWxJssdk(CustomerService.java:385)
	at com.fangxuele.fxl.service.v2.CustomerService$$FastClassBySpringCGLIB$$c0c26860.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.fangxuele.fxl.service.v2.CustomerService$$EnhancerBySpringCGLIB$$19c3a251.getWxJssdk(<generated>)

**Comment by cuter44** [comment]
RE @zzgf16

因为 [SHA-1 算法已证明可以被攻破](https://shattered.io/), 所以您所使用的版本的 jdk 已停用 SHA-1 算法验证. 微信 API 服务器的证书路径使用了 SHA-1, 因此被 jdk 拒绝.
这并非 wxpay-sdk 的问题.
在此我友情提供两个解决方案:
1. 使用较低版本的 jdk, 下策.
2. 参照 参考[2] 提供的说明在 jdk8 中强行启用 SHA1.

**以上两个方案都会带来安全风险.**

----

Due to [SHA-1 has been shattered](https://shattered.io/), your version of jdk has shut the usage of SHA1. And, wechat server's certificate chain contains SHA-1. So you encountered this error. 
After all, this is not our fault.
Here we provide two provisional measures:
1. Use an earlier version of jdk.
2. or, as reference [2] instructed, forcibly enable SHA-1

**Note that either of these will bring in security vulnerable.**

Thanks for reliance to Nyaguruware. ฅ(・ω・ฅ)

### References
1. JDK 8u141 Update Release Note - http://www.oracle.com/technetwork/java/javase/8u141-relnotes-3720385.html
2. JEP 288: Disable SHA-1 Certificates - https://bugs.openjdk.java.net/browse/JDK-8149555

**Comment by cuter44** [comment]
ADD:
Or try to specify `SSL_ALGORITHM=TLSv1.2` in `wxpay.properties` to see if it works.

**Comment by zzgf16** [comment]
谢谢cuter44的回复，我去测试一下具体那种方式解决比较帅，之后回复给大家
